name: Test Docker Build

on:
  pull_request:
    branches: [ master ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: charlesz54/debbit:test
        cache-from: type=gha
        cache-to: type=gha,mode=max 